platform/config/routes.rb
Platform::Application.routes.draw do

  get '/companies/:company_id/users/:user_id/time_offs/manage', :to => 'time_offs#manage'
  get '/companies/:company_id/users/:user_id/time_offs/:id/approve', :to => 'time_offs#approve'

#super_users
  match '/supersignin', to:'backoffice/super_user_sessions#new'
  match '/supersignout', to:'backoffice/super_user_sessions#destroy'
  match '/home', :to => 'backoffice/super_users#home'

#companies
  get '/companies/:company_id/users/verify', :to => 'rasocomp/users#verify'
  get '/companies/:company_id/users/:id/dashboard', :to => 'rasocomp/users#dashboard', as: 'user_dashboard'
  
  match '/companies/:company_id/signin', to:'rasocomp/user_sessions#new', as: 'company_signin'
  match '/companies/:company_id/signout', to:'rasocomp/user_sessions#destroy', as: 'company_signout'
#bills
  match '/bills', to: 'rasocomp/bills#show_all'

#static_pages
  match '/dashboard', :to => 'rasocomp/dashboard#start'
  
  #match '/aboutus' => 'staticpages#aboutus'
  #match '/ideas' => 'staticpages#ideas'
  #match '/contacts' => 'staticpages#contacts'

  #root :to => 'rasocomp/dashboard#start'
  root :to => 'frontoffice/frontoffice#index'

  scope :module => "backoffice" do
    resources :super_users
    resources :super_user_sessions, only: [:new, :create, :destroy]
  end

  scope :module => "rasocomp" do
    resources :companies do
      resources :users do
        member do
          put 'activate'
        end
	resources :time_offs
      end
      resources :bills
      resources :user_sessions, only: [:new, :create, :destroy]
    end
  end

    get '/homefront' , :to => 'frontoffice/frontoffice#index'
    get '/aboutus' , :to => 'frontoffice/frontoffice#aboutus'
    get '/idea' , :to => 'frontoffice/frontoffice#idea'
    get '/contacts' , :to => 'frontoffice/frontoffice#contacts'
    get '/signup', :to => 'frontoffice/frontoffice#new'
end

platform/app/models/time_off.rb
class TimeOff < ActiveRecord::Base
  attr_accessor :credits
  attr_accessible :days, :description, :end_date, :start_date, :state, :category, :user_id, :credits
  belongs_to :user


  before_validation :set_days

  validates :user_id, :presence => true

  validates :end_date, :presence => true,
                       :timeliness => { :after => lambda { :start_date },
                                        :after_message => ':end_date > :start_date',
                                        :type => :date}

  validates :start_date, :presence => true,
                         :timeliness => { :after => lambda { Date.current }, 
                                          :after_message => ':start_date > today',
                                          :type => :date}

  validates :category, :presence => true, 
                       :numericality => { :only_integer => true,
                                          :greater_than_or_equal_to => 0,
                                          :less_than_or_equal_to => 3 }

  validates :state, :presence => true, 
                    :numericality => { :only_integer => true,
                                       :greater_than_or_equal_to => -1,
                                       :less_than_or_equal_to => 1 }

  validates :days, :presence => true,
                   :numericality => { :onlu_integer => true,
                                      :greater_than_or_equal_to => 0 } 

  validates :credits, :presence => true,
                      :numericality => { :onlu_integer => true,
                                         :greater_than_or_equal_to => :days } 

  def days_diff
    (self.end_date - self.start_date).to_i
  end

  private
    def set_days
      self.days = days_diff
    end
end

platform/app/controllers/time_offs_controller.rb
class TimeOffsController < ApplicationController

  def index
    @company = Company.find( params[:company_id])
    @user = @company.users.find( params[:user_id])

    @timeoffs = @user.time_offs #TimeOff.find_by_user_id( params[:user_id])
  end

  def manage
    @company = Company.find( params[:company_id])
    @user = @company.users.find( params[:user_id])
    @timeoffs = TimeOff.all
  end

  def approve
    @company = Company.find( params[:company_id])
    @user = @company.users.find( params[:user_id])
    @timeoff = @user.time_offs.find( params[:id])
  end

  def disapprove
    redirect_to root_path
  end

  def set_state_to_valid
    
  end

  def show
    @timeoffs = TimeOff.find( params[:id])
  end

  def new
    @company = Company.find( params[:company_id])
    @user = @company.users.find( params[:user_id])
    @timeoff = @user.time_offs.build
  end

  def create
    @company = Company.find( params[:company_id])
    @user = @company.users.find( params[:user_id])
    @timeoff = @user.time_offs.build( params[:time_off])
    @timeoff.state = 0
    @timeoff.credits = @user.time_off_days
    if @timeoff.save
      @user.time_off_days -= @timeoff.days
      @user.save!(:validate => false)
      redirect_to company_user_time_offs_path( params[:company_id], params[:user_id])
    else
      render 'new'
    end
  end

  def destroy
    user = User.find( params[:user_id])
    timeoff = TimeOff.find( params[:id])
    user.time_off_days += timeoff.days
    user.save!(:validate => false)
    timeoff.destroy
    redirect_to company_user_time_offs_path( params[:company_id], params[:user_id])
  end
end

platform/app/helpers/time_offs_helper.rb
module TimeOffsHelper
end

platform/app/views/time_offs/approve.html.erb
APROVE TIME OFF

<%= form_for [@company, @user, @timeoff] do |f| %>
  <%= f.label :start_date %><br>
  <%= @timeoff.start_date %>
  <%= f.label :end_date %><br>
  <%= @timeoff.end_date %>
  <br>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Confirm") %>
<% end %>

platform/app/views/time_offs/index.html.erb
<h1> Time Offs </h1>
<br/>
<h1>CREDITS <%= @user.time_off_days %></h1><br>
<%= link_to 'click here avoit work', new_company_user_time_off_path( @company, @user) %><br>

<% @timeoffs.each do |t| %>
  Timeoff id: <%= t.id %>;
  Start: <%= t.start_date %>;
  End: <%= t.end_date %>;
  Days: <%= t.days %>;
  Type: <%= t.category %>;
  State: <%= t.state %>;
  Desc: <%= t.description %>;
  <%= link_to "cancel", [@company, @user, t], :method => :delete, :data => { :confirm => 'Confirmation Box'} %>
  <br/>
<% end %>
<br/>
<br/>

platform/app/views/time_offs/manage.html.erb
GESTOR<br>
LISTAR TODOS TIMEOFFS DE TODOS PARA GERIR<br>
<%= @user.name %><br><br>
<% @timeoffs.each do |t| %>
  USER ID:<%= t.user_id%><br>
  TIMEOFF ID:<%= t.id %><br>
  TIMEOFF STATE:<%= t.state %><br>
  <br>
  <%= link_to "disapprove", [ @company, @user, t], :method => :put, :data => { :confirm => 'Confirmation Box'} %>
  <br>
  <hr>
<% end %>

platform/app/views/time_offs/new.html.erb
TIME OFF
<%= form_for [@company, @user, @timeoff] do |f| %>
  <% @timeoff.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
  <%= f.select :category, [["CANCRO", 1],["DORMIR", 2]] %>
  <%= f.label :start_date %>
  <%= f.date_select :start_date %>
  <%= f.label :end_date %>
  <%= f.date_select :end_date %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>