platform/config/routes.rb
Platform::Application.routes.draw do

  get '/companies/:company_id/users/:user_id/time_offs/manage', :to => 'time_offs#manage'
  get '/companies/:company_id/users/:user_id/time_offs/:id/approve', :to => 'time_offs#approve'

#super_users
  match '/supersignin', to:'backoffice/super_user_sessions#new'
  match '/supersignout', to:'backoffice/super_user_sessions#destroy'
  match '/home', :to => 'backoffice/super_users#home'

#companies
  get '/companies/:company_id/users/verify', :to => 'rasocomp/users#verify'
  get '/companies/:company_id/users/:id/dashboard', :to => 'rasocomp/users#dashboard', as: 'user_dashboard'
  
  match '/companies/:company_id/signin', to:'rasocomp/user_sessions#new', as: 'company_signin'
  match '/companies/:company_id/signout', to:'rasocomp/user_sessions#destroy', as: 'company_signout'
#bills
  match '/bills', to: 'rasocomp/bills#show_all'

#static_pages
  match '/dashboard', :to => 'rasocomp/dashboard#start'
  
  #match '/aboutus' => 'staticpages#aboutus'
  #match '/ideas' => 'staticpages#ideas'
  #match '/contacts' => 'staticpages#contacts'

  #root :to => 'rasocomp/dashboard#start'
  root :to => 'frontoffice/frontoffice#index'

  scope :module => "backoffice" do
    resources :super_users
    resources :super_user_sessions, only: [:new, :create, :destroy]
  end

  scope :module => "rasocomp" do
    resources :companies do
      resources :users do
        member do
          put 'activate'
        end
	resources :time_offs
      end
      resources :bills
      resources :user_sessions, only: [:new, :create, :destroy]
    end
  end

    get '/homefront' , :to => 'frontoffice/frontoffice#index'
    get '/aboutus' , :to => 'frontoffice/frontoffice#aboutus'
    get '/idea' , :to => 'frontoffice/frontoffice#idea'
    get '/contacts' , :to => 'frontoffice/frontoffice#contacts'
    get '/signup', :to => 'frontoffice/frontoffice#new'
end

platform/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  company_id      :integer
#  email           :string(255)
#  role            :integer
#  name            :string(255)
#  state           :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :company_id, :email, :name, :role, :time_off_days, :state, :password, :password_confirmation
  has_secure_password
  belongs_to :company
  has_many :time_offs

  before_save :create_remember_token

  validates :name, :presence => true, :length => { :maximum => 20}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true,
                    :format => { :with => VALID_EMAIL_REGEX },
                    :uniqueness => { :case_sensitive => false }

  validates :password,  :length => { :minimum => 6 },
                        :if => :verified?
  validates :password_confirmation, :presence => true,
                                    :if => :verified?
  validates :role, :numericality => { :only_integer => true, 
                                      :greater_than_or_equal_to => 0,
                                      :less_than_or_equal_to => 10 }

  validates :state, :numericality => { :only_integer => true,
                                       :greater_than_or_equal_to => -1,
                                       :less_than_or_equal_to => 1 }
  
  def verified?
    self.state != -1
  end

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

platform/app/controllers/rasocomp/application_controller.rb
class Rasocomp::ApplicationController < ::ApplicationController
  layout "rasoemp"
end

platform/app/controllers/rasocomp/bills_controller.rb
class Rasocomp::BillsController < Rasocomp::ApplicationController
  before_filter :super_user_or_manager, :only => [:show, :index]
  before_filter :super_user_only, :only => :show_all

  def show
    @bill = Company.find(params[:company_id]).bills.find(params[:id])
  end

  def index
    @company = Company.find(params[:company_id])
    @bills = @company.bills.order("created_at Desc").paginate(:page => params[:page], :per_page => 4) 
  end

  def show_all
      @bills = Bill.search(params[:search], params[:order], params[:filt]).paginate(:page => params[:page], :per_page => 4)
  end

  private
    def super_user_or_manager
      @comp = Company.find(params[:company_id])
      redirect_to company_signin_path(params[:company_id]), notice: t(:no_permission_to_access) unless manager_signed_in?(@comp.tag) || super_user_signed_in?
    end

  private
    def super_user_only
      redirect_to supersignin_path, notice: t(:no_permission_to_access) unless super_user_signed_in?
    end
end

platform/app/controllers/rasocomp/companies_controller.rb
class Rasocomp::CompaniesController < Rasocomp::ApplicationController
  before_filter :super_user_or_manager_or_root, :only => [:show, :edit, :update]
  before_filter :super_user_only, :only => :index

  def index
    @companies = Company.search(params[:search], params[:order]).paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @companies = Company.search(nil, params[:order]).paginate(:page => params[:page], :per_page => 10)
    @company = Company.find(params[:id])
    @bills = @company.bills
  end

  def edit
    @company = Company.find( params[:id])
  end

  def update
    @company = Company.find( params[:id])
    if @company.update_attributes(params[ :company])
      flash[:success]= t(:successful_update)
      redirect_to edit_company_path @company.id
    else
      render 'edit'
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new( params[:company])
    @company.state = 0;
    if @company.save
      user = @company.users.build
      user.name = 'root'
      user.email = @company.email
      user.state = -1
      user.role = 0
      user.password_digest = 0
      user.save
      UserMailer.verification_email(user).deliver
      redirect_to company_path @company.id
    else
      render 'new'
    end
  end

  private
    def super_user_or_manager_or_root
      @comp = Company.find(params[:id])
      redirect_to company_signin_path(@comp), notice: t(:no_permission_to_access) unless manager_signed_in?(@comp.tag) || root_signed_in?(@comp.tag) || super_user_signed_in?
    end

  private
    def super_user_only
      redirect_to supersignin_path, notice: t(:no_permission_to_access) unless super_user_signed_in?
    end
end

platform/app/controllers/rasocomp/dashboard_controller.rb
class Rasocomp::DashboardController < Rasocomp::ApplicationController
  def index
  end
  
  def start
  end
end

platform/app/controllers/rasocomp/user_sessions_controller.rb
class Rasocomp::UserSessionsController < Rasocomp::ApplicationController
  layout "nolayout"
  def new
  end

  def create
    company = Company.find(params[:company_id])
    user = company.users.find_by_email(params[:user_session][:email].downcase)
    #use some base64 for company ?
    if user && user.authenticate(params[:user_session][:password])
      sign_in_user(user, company.tag)
      redirect_to user_dashboard_path company, user
    else
      flash.now[:error] = t(:invalid_login)
      render 'new'
    end
  end

  def destroy
    company = Company.find(params[:company_id])
    user_sign_out company.tag
    redirect_to root_path
  end


end

platform/app/controllers/rasocomp/users_controller.rb
class Rasocomp::UsersController < Rasocomp::ApplicationController
  before_filter :super_user_or_manager_or_root, :only => [:new, :create, :index]
  before_filter :super_user_or_manager_or_user_self, :only => [:show, :edit, :update, :dashboard]
  #before_filter :super_user_or_manager, :only => [:index]

  def show
    @company = Company.find(params[:company_id])
    @user = @company.users.find(params[:id])
  end

  def index
    @company = Company.find(params[:company_id])
    @users = @company.users
  end

  def edit
    @company = Company.find( params[:company_id] )
    @user = @company.users.find( params[:id])
  end

  def update
    @company = Company.find( params[:company_id])
    @user = @company.users.find( params[:id])
    if @user.update_attributes( params[:user])
      redirect_to user_dashboard_path @company.id, @user
    else
      render 'edit'
    end
  end

  def activate
    @company = Company.find( params[:company_id])
    @user = @company.users.find( params[:id])
    if @user.state == -1
      @user.state = 1
    end
    if @user.update_attributes( params[:user])
      flash[:success] = t(:account_activated)
      redirect_to company_path @company.id
    else
      render 'verify'
    end
  end

  def verify
    if !params[:token] || !params[:company_id]
      flash[:error] = t(:invalid_verification)
      redirect_to root_path
    else
      @company = Company.find(params[:company_id])
      @user = @company.users.find_by_remember_token(params[:token])

      if @user.nil? || @user.state != -1
        flash[:error] = t(:invalid_verification)
        #redirect_to root_path
      end
    end
  end

  def new
    @company = Company.find( params[:company_id])
    @user = @company.users.build
    @roles = ROLE
  end

  def create
    @roles = ROLE
    @company = Company.find( params[:company_id])
    role = params[:user][:role]
    params[:user].delete(:role)
    @user = @company.users.build( params[:user])
    @user.role = Integer role
    @user.state = -1
    @user.password_digest = 0
    if @user.save
      UserMailer.verification_email(@user).deliver
      redirect_to company_users_path
    else
      render 'new'
    end
  end

  def dashboard
    @company = Company.find(params[:company_id])
    @user = @company.users.find(params[:id])
  end

  private
    def super_user_or_manager_or_root
      comp = Company.find(params[:company_id])
      redirect_to company_signin_path(comp), notice: t(:no_permission_to_access) unless manager_signed_in?(comp.tag) || root_signed_in?(comp.tag) || super_user_signed_in?
    end

  private
    def super_user_or_manager_or_user_self
      comp = Company.find(params[:company_id])
      redirect_to company_signin_path(comp), notice: t(:no_permission_to_access) unless manager_signed_in?(comp.tag) || super_user_signed_in? || (user_signed_in?(comp.tag) && current_user(comp.tag).id == Integer(params[:id]))
    end

  private
    def super_user_or_manager
      comp = Company.find(params[:company_id])
      redirect_to company_signin_path(comp), notice: t(:no_permission_to_access) unless manager_signed_in?(comp.tag) || super_user_signed_in?
    end
end

platform/app/helpers/users_helper.rb
module UsersHelper
end

platform/app/views/rasocomp/users/dashboard.html.erb
<div class="row">
	<div class="three columns push-nine">

			<div class=" twelve columns row collapse">
			  <div class="eight mobile-four columns">
			    <input type="text" />
			  </div>
			  <div class="four mobile-one columns">
			    <a class="button expand postfix">Search</a>
			  </div>
			</div>

			<div class="twelve columns" style="padding-bottom:20px">
				<a href="#" class="th"><img src="http://placehold.it/200x200" alt="Foto da Pessoa"></a>
			</div>

			<div class="twelve columns" style="padding-bottom:20px">
				<div class="panel callout radius">
			      <h5>Formações</h5>
			      <p>Texto aqui</p>
			    </div>
		    </div>
			<div class="twelve columns" style="padding-bottom:20px">
				<div class="panel">
			      <h5>Calendário</h5>
			      <p>Texto aqui</p>
			    </div>
		    </div>
	</div> 
	<!-- Cena Grande -->
	<div class="nine columns pull-three">
			<dl class="tabs">
			  <dd class="active"><a href="#dashboard">Dashboard</a></dd>
			  <dd><a href="#profile">Profile</a></dd>
			  <dd><a href="#contract">Contract</a></dd>
			</dl>
			<ul class="tabs-content">
			  <li class="active" id="dashboardTab">

			  	<h4> Alertas </h4>

					<div class="alert-box">
						This is a standard alert (div.alert-box).
					 
					</div>

					<div class="alert-box success">
					  This is a success alert (div.alert-box.success).
					  <a href="" class="close">&times;</a>
					</div>

					<div class="alert-box alert">
					  This is an alert (div.alert-box.alert)
					</div>

					<%= link_to "company", company_path(@company), :class=>"button" %>
					<%= link_to "users list", company_users_path(@company), :class=>"button" %>


			  	<hr/>
			  	<h4> Time Offs </h4>
				<div class="button-bar">
					<ul class="button-group">
						<li><a href="#" class="button">Book Holidays</a></li>
					</ul>

					<ul class="button-group">
					    <li><a href="#" class="button">Call In Sick</a></li>
					</ul>
				</div>
			  </li>
			  <li id="profileTab">

			  	<h3> User Profile </h3>
			  	<hr/>
			  	<p><span class=" radius label">User Name</span><span> <%= @user.name %></span></p>
			  	<p><span class="radius label">User Email</span><span> <%= @user.email %></span></p>
			  	<div style:"text-alig">

				<%= link_to "Edit", edit_company_user_path(@company, @user), :class=>"button" %>
			  	</div>

			  </li>
			  <li id="contractTab">

				<h3> Contract </h3>
			  	<hr/>
			  	<p><span class=" radius label">Job Title</span><span> Job Title</span></p>
			  	<p><span class=" radius label">Begin Date</span><span> Date</span></p>
			  	<p><span class=" radius label">End Date</span><span> Date</span></p>
			  </li>
			</ul>
		</div>


</div>

platform/app/views/rasocomp/users/edit.html.erb
<div class="row">
  <div class="three columns push-nine">

      <div class=" twelve columns row collapse">
        <div class="eight mobile-four columns">
          <input type="text" />
        </div>
        <div class="four mobile-one columns">
          <a class="button expand postfix">Search</a>
        </div>
      </div>

      <div class="twelve columns" style="padding-bottom:20px">
        <a href="#" class="th"><img src="http://placehold.it/200x200" alt="Foto da Pessoa"></a>
      </div>

      <div class="twelve columns" style="padding-bottom:20px">
        <div class="panel callout radius">
            <h5>Formações</h5>
            <p>Texto aqui</p>
          </div>
        </div>
      <div class="twelve columns" style="padding-bottom:20px">
        <div class="panel">
            <h5>Calendário</h5>
            <p>Texto aqui</p>
          </div>
        </div>


</div> 
  <!-- Cena Grande -->
  <div class="nine columns pull-three">

        <h3> Edit User Profile </h3>
        <hr/>
          <%= form_for [@company, @user] do |f| %>

            <span class=" radius label">User Name</span>
            <%= f.text_field :name %>

          <span class="radius label">User Email</span>
            <%= f.text_field :email %>

          <span class=" radius label">Password</span>
            <%= f.password_field :password %>

          <span class=" radius label">Comfirm Password</span>
            <%= f.password_field :password_confirmation %>
        
            <p style="text-align: center"><%= f.submit 'Save!', :class => "button" %></p>

            
            <% if @user.errors.any? %> <span class=" radius label">Error Messages</span>
            <hr/>
            <% end %>
            <% @user.errors.full_messages.each do |msg| %>
              <p><%= msg %></p>
            <% end %>
          <% end %>




  </div>
</div>

platform/app/views/rasocomp/users/index.html.erb
<div class="row">
	<div class="twelve columns">

			<h3>Company employees</h3>
	</div>
</div>

<div class="row">
	<div class="nine columns">
		<!-- Listagem -->
		<div class="panel">
			<div class="row">
				<div class="twelve columns">
					<table class="twelve tableJobs">
						<thead>
							<tr>
								<th>Cod.</th>
								<th>Name</th>
								<th>E-Mail</th>
								<th>Role</th>
								<th>Profile</th>
								<!--<th>Status</th>-->
							</tr>
						</thead>
						<tbody>
							<% @users.each do |u| %>
								<tr>
							    	<td><%= u.id %></td>
							      	<td><%= u.name %></td>
							      	<td><%= u.email %></td>
							 
							      	<td><%= t(ROLE.invert[u.role]) %></td>
							      	<td><%= link_to "Profile", company_user_path(u.company_id, u) %> </td>

							      	<!-- <td>
							      		<form class="custom" style="margin:0;"><label for="checkbox1"><input type="checkbox" id="checkbox1" style="display: none;"><span class="custom checkbox"></span></label></form>
							      	</td> -->
							    </tr>
  <br/>
<% end %>




						</tbody>
					</table>
				</div>
			</div>
			<div class="row">
				<div class="eight columns">
					<ul class="pagination">
						<li class="arrow unavailable"><a href="">&laquo;</a></li>
						<li class="current"><a href="">1</a></li>
						<li><a href="">2</a></li>
						<li><a href="">3</a></li>
						<li><a href="">4</a></li>
						<li class="unavailable"><a href="">&hellip;</a></li>
						<li><a href="">12</a></li>
						<li><a href="">13</a></li>
						<li class="arrow"><a href="">&raquo;</a></li>
					</ul>
				</div>
				<div class="four columns">
					<div class="row collapse">
				  		<div class="eight mobile-four columns">
				    		<input type="text" />
				  		</div>
				  		<div class="four mobile-one columns">
				    		<a class="button expand postfix">Search</a>
				  		</div>
					</div>
				</div>
			</div>	
		</div>
			<!-- Fim Listagem -->
	</div>
	<div class="three columns">
		<div class="panel callout radius">
		    <h5>Add User</h5>
			<% if (current_user( @company.tag).role == ROOT || current_user( @company.tag).role == ROLE[:manager])  %>
				<%= link_to "Add User", new_company_user_path( @company, params[:id]), :class=>"button" %>
        	<% end %>
		</div>
	</div>
</div>
<br/>

<br/>
<br/>

platform/app/views/rasocomp/users/new.html.erb
<div class="row">
  <div class="twelve columns">
    <h2> Add new User</h2>
    <hr/>
<%= form_for [@company, @user] do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>

  <p class=" radius label">Name</p>
  <%= f.text_field :name %>

  <p class=" radius label">Email</p>
 <%= f.email_field :email %>

  <p class=" radius label">Role</p>
  <%= f.select :role, ROLE %>
  
  <p style="text-align: center"><%= f.submit :class => "button" %></p>
<% end %>
</div>
</div>

platform/app/views/rasocomp/users/show.html.erb
<div class="row">
	<div class="twelve columns">
		<h3> User Profile </h3>
		<hr/>
		<p><span class=" radius label">User ID</span><span> <%= @user.id %></span></p>
		<p><span class=" radius label">User Name</span><span> <%= @user.name %></span></p>
		<p><span class="radius label">User Email</span><span> <%= @user.email %></span></p>
		<p><span class=" radius label">User Role</span><span> <%= @user.role %></span></p>
		<div style:"text-alig">
			<%= link_to "Edit", edit_company_user_path(@company, @user), :class=>"button" %>
		</div>
	</div>
</div>

platform/app/views/rasocomp/users/verify.html.erb
<div class="row">
	<div class="twelve columns">
		<div id="signup">
			<h3> Verify User </h3>
			<hr/>
			<%= form_for [@company, @user], :url => activate_company_user_path(@company, @user) do |f| %>
			  <% @user.errors.full_messages.each do |error| %>
			    <li><%= error %></li>
			  <% end %>

			  <span class=" radius label">Password</span>
			  <%= f.password_field :password %>

			  <span class=" radius label">Confirm Password</span>
			  <%= f.password_field :password_confirmation %>

			  <p style="text-align: center"><%= f.submit 'Comfirm Account', :class => "button" %></p>
			<% end %>
		</div>
	</div>
</div>